# ingress-nginx:
#   controller:
#     service:
#       externalTrafficPolicy: "Local"
#       annotations:
#         service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
#         service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
#         service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#         service.beta.kubernetes.io/aws-load-balancer-type: nlb
#         service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#         service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https


controller:
  kind: DaemonSet
  electionID: ingress-controller-leader  
  ingressClassResource:
    default: true
    name: nginx-tls
  ingressClass: nginx-tls	
  # replicaCount: 2   # Dev Cluster 에서만 Deploy Prod 에서는 주석처리할것 (Daemonset)
  metrics:
    enabled: false  # zum dev는 false 입니다.  zum prod 도 false 처리 했습니다.
    service:
      annotations: 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
    serviceMonitor:
      enabled: true
  service:
    #externalTrafficPolicy: Cluster
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: true
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0b8b02f5f559e65b6,subnet-0e3639679afd9af3b,subnet-06f3e33b54b7e9761
      #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  allowSnippetAnnotations: true  # 2024-05-23 dev 에서 적용하였고 prod도 반영하려면 주석 풀고 패치 해야함.
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  config:
    # use-forwarded-headers: "true"  # 클라이언트 IP 추적
    # use-proxy-protocol: "true"
    dummy-key: "dummy-value2"
defaultBackend:
  enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb