apiVersion: karpenter.k8s.aws/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    instanceProfile: "karpenter-workspace1-20250317045252276100000012"
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m5.large", "m5.xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["ap-northeast-2a", "ap-northeast-2b","ap-northeast-2c"]
    - key: "karpenter.k8s.aws/discovery"
      operator: Exists
  limits:
    resources:
      cpu: "1000"
      memory: "1000Gi"
  ttlSecondsAfterEmpty: 30

